server:
  port: 5050

spring:
  application:
    name: summarizer-api

  jackson:
    default-property-inclusion: non_null

  data:
    redis:
      url: redis://default:AWSWAAIncDIxODkyM2RhNWUyN2Q0NWMyOWRjM2RjMzRhY2IzN2JmZXAyMjU3NTA@more-cub-25750.upstash.io:6379
      timeout: 2s

gemini:
  api-key: AIzaSyDEb5Fj2ECz2Ol6xOq1lkfxsieqARMPqqU
  model: gemini-2.5-flash-lite
  endpoint: https://generativelanguage.googleapis.com/v1beta/models
  timeout: 10s

logging:
  level:
    root: INFO
